=== inxi
Mostrar información detallada del sistema y del hardware.

[source,bash]
----
# Mostrar información básica del sistema
inxi
----

* -F:: `inxi -F` Mostrar información completa (full)

[source,bash]
----
# Mostrar información completa del sistema
inxi -F
----

* -Fx:: `inxi -Fx` Información completa y extendida

[source,bash]
----
# Mostrar información completa con detalles adicionales
inxi -Fx
----

* -A:: `inxi -A` Información de audio

[source,bash]
----
# Mostrar dispositivos de audio
inxi -A
----

* -B:: `inxi -B` Información de batería

[source,bash]
----
# Mostrar estado de la batería
inxi -B
----

* -C:: `inxi -C` Información de CPU

[source,bash]
----
# Mostrar información del procesador
inxi -C
----

* -D:: `inxi -D` Información de discos

[source,bash]
----
# Mostrar información de discos y almacenamiento
inxi -D
----

* -G:: `inxi -G` Información gráfica (GPU y drivers)

[source,bash]
----
# Mostrar información gráfica
inxi -G
----

* -I:: `inxi -I` Información general (hostname, distro, kernel, uptime)

[source,bash]
----
# Mostrar información general del sistema
inxi -I
----

* -M:: `inxi -M` Información de placa base

[source,bash]
----
# Mostrar información de la motherboard
inxi -M
----

* -N:: `inxi -N` Información de red

[source,bash]
----
# Mostrar información de interfaces de red
inxi -N
----

* -R:: `inxi -R` Información de repositorios

[source,bash]
----
# Mostrar información de repositorios configurados
inxi -R
----

* -S:: `inxi -S` Información del sistema operativo

[source,bash]
----
# Mostrar información del sistema
inxi -S
----

* -m:: `inxi -m` Información de memoria (RAM)

[source,bash]
----
# Mostrar información de memoria
inxi -m
----

* -o:: `inxi -o` Información de particiones montadas

[source,bash]
----
# Mostrar información de sistemas de archivos montados
inxi -o
----

* -p:: `inxi -p` Información de particiones (requiere root)

[source,bash]
----
# Mostrar tabla de particiones
sudo inxi -p
----

* -t:: `inxi -t` Mostrar procesos y uso de recursos

[source,bash]
----
# Mostrar top de procesos
inxi -t
----

* -z:: `inxi -z` Ocultar información sensible (MAC, IP)

[source,bash]
----
# Mostrar información anonimizando datos sensibles
inxi -z
----

* --help:: `inxi --help` Mostrar ayuda del comando

[source,bash]
----
# Mostrar ayuda
inxi --help
----

* --version:: `inxi --version` Mostrar versión de inxi

[source,bash]
----
# Mostrar versión instalada
inxi --version
----

